### PR TITLE
Add zincby command http://redis.io/commands/zincrby

### PR DESCRIPTION
**Pull request by kjsteuer**
@kevin-cantwell :eyes:

### CODE REVIEW

**Comment by kevin-cantwell** [comment]
Cool. Can you also add this to the `NoResultCommands` interface?

**Comment by kevin-cantwell** [comment]
You'll actually need to add this to the `sendOnlyConnection` struct and `Commands` interface as well

**Comment by kjsteuer** [comment]
Yeah will add to those to the NoResults. I missed the pipelined changes on my commit, otherwise I don't think it would have compiled.

**Comment by kjsteuer** [comment]
oh n/m the pipelined file is only used by NoResultCommands

**Comment by kjsteuer** [comment]
@kevin-cantwell Should be ready now.

**Comment by kevin-cantwell** [comment]
Murj

**Pull request merged**
